name: pvXAction Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore pvX.Utils.sln
    
    - name: Build solution
      run: msbuild pvX.Utils.sln -t:rebuild -property:Configuration=Release

    - name: Pack NuGet package
      run: nuget pack Utils/pvX.Utils.csproj -Properties Configuration=Release -Version 1.4.3
          
    - name: Push NuGet package to Azure Artifacts
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        nuget push -Source "pvx.Utils" -ApiKey az *.nupkg
