name: pvXAction Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore pvX.Utils.sln
    
    - name: Build solution
      run: msbuild pvX.Utils.sln -t:rebuild -property:Configuration=Release

    - name: Pack NuGet package
      run: nuget pack Utils/pvX.Utils.csproj -Properties Configuration=Release -Version 1.4.4

    - name: Add NuGet package Source
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        nuget sources Add -Name "pvx.Utils" -Source "https://pkgs.dev.azure.com/pvx-cad/pvX.Utils/_packaging/pvx.Utils/nuget/v3/index.json"
        
    - name: Push NuGet package to Azure Artifacts
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/pvx-cad/pvX.Utils/_packaging/pvX.Utils/nuget/v3/index.json", "username":"orcun@pvx.ai", "password":"${{ secrets.AZURE_DEVOPS_PAT }}"}]}'
      run: |
        nuget push -Source "pvx.Utils" -ApiKey az -NonInteractive *.nupkg
        
